# Generated by Django 3.2.4 on 2021-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210625_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
